
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sabaghasemzadehhassankolaei
 */
public class addCredit extends javax.swing.JFrame {

    /**
     * Creates new form addCredit
     */
    public addCredit() {
        initComponents();
        loadCredit();
        creditField.getDocument().addDocumentListener(new addCredit.BecomingRedDocumentListener3(creditField, addBtn));

    }
    
    private void addCredit() {
        try {
            double currentCredit = loadCredit();

            // Add the specified amount to the current credit
            double amountToAdd = Double.parseDouble(creditField.getText());
            double updatedCredit = currentCredit + amountToAdd;

            // Write the updated credit back to the file
            saveCredit(updatedCredit);

            JOptionPane.showMessageDialog(this, "Credit added successfully. New credit: " + updatedCredit);
        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error occurred while adding credit.");
        }
        
        creditField.setText("0.0");
    }


    private double loadCredit() {
        try {
            File creditFile = new File("credit.txt");
            if (!creditFile.exists()) {
                // Create the file if it doesn't exist
                createDefaultCreditFile();
            } else {
                // Open the file for reading
                BufferedReader reader = new BufferedReader(new FileReader(creditFile));

                String line = reader.readLine();

                // If the file is empty, initialize credit to 0
                if (line == null || line.isEmpty()) {
                    currentCreditlbl.setText("0.0");
                } else {
                    double currentCredit = Double.parseDouble(line);
                    currentCreditlbl.setText(Double.toString(currentCredit));
                }

                reader.close();
            }
        } catch (IOException | NumberFormatException e) {
            e.printStackTrace();
        }
        
        return Double.parseDouble(currentCreditlbl.getText());
        
    }



    private void saveCredit(double credit) throws IOException {
        try (BufferedWriter writer = new BufferedWriter(new FileWriter("credit.txt"))) {
            writer.write(Double.toString(credit));
        }
    }

    private void createDefaultCreditFile() throws IOException {
        try (BufferedWriter writer = new BufferedWriter(new FileWriter("credit.txt"))) {
            writer.write("0.0");
        }
    }
    
    private static class BecomingRedDocumentListener3 implements DocumentListener {
        private JTextField textField;
        private JButton setButton;

        public BecomingRedDocumentListener3(JTextField textField, JButton setButton) {
            this.textField = textField;
            this.setButton = setButton;
        }

        @Override
        public void insertUpdate(DocumentEvent e) {
            updateComponents();
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            updateComponents();
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
            updateComponents();
        }

        private void updateComponents() {
            String text = textField.getText();
            try {
                if (text.isEmpty() ||!text.chars().allMatch(Character::isDigit)) {
                    setButton.setEnabled(false); // Disable the set button
                } else {
                    setButton.setEnabled(true); // Enable the set button
                }
            } catch (NumberFormatException ex) {
                setButton.setEnabled(false); // Disable the set button
            }
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        creditField = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        currentCreditlbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Chakra Petch", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("amount to add:");

        jButton1.setBackground(new java.awt.Color(251, 255, 203));
        jButton1.setFont(new java.awt.Font("Chakra Petch", 0, 13)); // NOI18N
        jButton1.setText("go back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Chakra Petch", 0, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Current credit:");

        creditField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditFieldActionPerformed(evt);
            }
        });

        addBtn.setBackground(new java.awt.Color(205, 255, 211));
        addBtn.setFont(new java.awt.Font("Chakra Petch", 0, 13)); // NOI18N
        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        currentCreditlbl.setFont(new java.awt.Font("Chakra Petch", 0, 13)); // NOI18N
        currentCreditlbl.setForeground(new java.awt.Color(255, 255, 255));
        currentCreditlbl.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(currentCreditlbl))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(creditField, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(addBtn))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentCreditlbl)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creditField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(24, 24, 24)
                .addComponent(addBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        // Parse the current credit from the label
        // Parse the current credit from the label
        double currentCredit = Double.parseDouble(currentCreditlbl.getText());
        double amountToAdd = Double.parseDouble(creditField.getText());
        double updatedCredit = currentCredit + amountToAdd;


        SwingUtilities.invokeLater(() -> {
        currentCreditlbl.setText(Double.toString(updatedCredit));
        });

        // Add the credit after updating the label
        addCredit();
     

    }//GEN-LAST:event_addBtnActionPerformed

    private void creditFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        horseStatsDisplay stats = new horseStatsDisplay();
        stats.show();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addCredit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addCredit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addCredit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addCredit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addCredit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField creditField;
    private javax.swing.JLabel currentCreditlbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
