
import java.awt.Color;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JLabel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sabaghasemzadehhassankolaei
 */
public class betHistoryDisplay extends javax.swing.JFrame {

    /**
     * Creates new form betHistory
     */
    public betHistoryDisplay() {
        initComponents();
        loadBetHistory();
    }

    private void loadBetHistory() {
        int wins = 0;
        int losses = 0;
        
        try (BufferedReader reader = new BufferedReader(new FileReader("bet_history.txt"))) {
            String line;         
            int row = 0; // Row counter for positioning JLabels
            while ((line = reader.readLine()) != null) {
                // Split the line into bet and result
                String[] parts = line.split(",");
                String bet = parts[0];
                String result = parts[1];
                String amount = parts[2];
                
                
                // Update wins or losses count based on the result
                if (result.equals("won")) {
                    wins++;
                } else if (result.equals("lost")) {
                    losses++;
                }

                // Create JLabels to display bet history
                javax.swing.JLabel betLabel = new javax.swing.JLabel();
                javax.swing.JLabel resultLabel = new javax.swing.JLabel();
                javax.swing.JLabel amountLabel = new javax.swing.JLabel();



                // Set text for JLabels
                betLabel.setText(bet);
                resultLabel.setText(result);
                amountLabel.setText(amount);
                
                betLabel.setForeground(Color.WHITE);
                resultLabel.setForeground(Color.WHITE);
                amountLabel.setForeground(Color.WHITE);


                // Set positions for JLabels
                betLabel.setBounds(10, 37 + row * 30, 100, 20);
                resultLabel.setBounds(150, 37 + row * 30, 100, 20);
                amountLabel.setBounds(265, 37 + row * 30, 100, 20);

                // Add JLabels to jPanel1
                jPanel1.add(betLabel);
                jPanel1.add(resultLabel);
                jPanel1.add(amountLabel);

                row++; // Increment row counter
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        
        provideInsights(wins,losses);
    }
    
    private void provideInsights(int wins, int losses) {
        String insight;
        if (wins == 0 && losses == 0) {
            insight = "No betting history available.";
        } else {
            double winningPercentage = (double) wins / (wins + losses) * 100;
            if (winningPercentage >= 50) {
                insight = "Your winning percentage is " + String.format("%.2f", winningPercentage) + "%. Keep up the good work!";
            } else {
                insight = "Your winning percentage is " + String.format("%.2f", winningPercentage) + "%. Consider adjusting your betting strategy.";
            }
        }
        insightlbl.setText(insight);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        insightlbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        returnBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Chakra Petch", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(211, 255, 211));
        jLabel1.setText("Horse Bet");

        jLabel2.setFont(new java.awt.Font("Chakra Petch", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(211, 255, 211));
        jLabel2.setText("result");

        insightlbl.setFont(new java.awt.Font("Chakra Petch", 0, 13)); // NOI18N
        insightlbl.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Chakra Petch", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(211, 255, 211));
        jLabel3.setText("amount");

        returnBtn.setBackground(new java.awt.Color(196, 235, 255));
        returnBtn.setFont(new java.awt.Font("Chakra Petch", 0, 13)); // NOI18N
        returnBtn.setText("return");
        returnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(48, 48, 48)
                        .addComponent(jLabel2)
                        .addGap(73, 73, 73)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(returnBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(insightlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 115, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(returnBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 353, Short.MAX_VALUE)
                .addComponent(insightlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void returnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBtnActionPerformed
        // TODO add your handling code here:
        horseStatsDisplay display = new horseStatsDisplay();
        display.show();
        dispose();
    }//GEN-LAST:event_returnBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(betHistoryDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(betHistoryDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(betHistoryDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(betHistoryDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new betHistoryDisplay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel insightlbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton returnBtn;
    // End of variables declaration//GEN-END:variables
}
