
import java.awt.Color;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sabaghasemzadehhassankolaei
 */
public class setHorses extends javax.swing.JFrame {
    private Map<String, ImageIcon> horseData = new LinkedHashMap<>();
    private Map<String, Double> horseConfidence = new LinkedHashMap<>();


    /**
     * Creates new form startPage
     */
    public setHorses() {
        
        initComponents();
        horse1CoatComboBox.setEnabled(false);
        horse2CoatComboBox.setEnabled(false);
        horse3CoatComboBox.setEnabled(false);
        horse4CoatComboBox.setEnabled(false);
        horse5CoatComboBox.setEnabled(false);

        
        // Add document listeners to the text fields
        horse1NameField.getDocument().addDocumentListener(new enablingCombo1(horse1NameField));
        horse2NameField.getDocument().addDocumentListener(new enablingCombo2(horse2NameField));
        horse3NameField.getDocument().addDocumentListener(new enablingCombo3(horse3NameField));
        horse4NameField.getDocument().addDocumentListener(new enablingCombo4(horse4NameField));
        horse5NameField.getDocument().addDocumentListener(new enablingCombo5(horse5NameField));
        
        horse1Confidence.getDocument().addDocumentListener(new BecomingRedDocumentListener(horse1Confidence, jButton1));
        horse2Confidence.getDocument().addDocumentListener(new BecomingRedDocumentListener(horse2Confidence, jButton1));
        horse3Confidence.getDocument().addDocumentListener(new BecomingRedDocumentListener(horse3Confidence, jButton1));
        horse4Confidence.getDocument().addDocumentListener(new BecomingRedDocumentListener(horse4Confidence, jButton1));
        horse5Confidence.getDocument().addDocumentListener(new BecomingRedDocumentListener(horse5Confidence, jButton1));

    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        horse1NameField = new javax.swing.JTextField();
        horse2NameField = new javax.swing.JTextField();
        horse3NameField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        horse1CoatComboBox = new javax.swing.JComboBox<>();
        horse2CoatComboBox = new javax.swing.JComboBox<>();
        horse3CoatComboBox = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        horse1Confidence = new javax.swing.JTextField();
        horse2Confidence = new javax.swing.JTextField();
        horse3Confidence = new javax.swing.JTextField();
        horse4Confidence = new javax.swing.JTextField();
        horse4CoatComboBox = new javax.swing.JComboBox<>();
        horse4NameField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        horse5Confidence = new javax.swing.JTextField();
        horse5CoatComboBox = new javax.swing.JComboBox<>();
        horse5NameField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        horsesNum = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        lengthField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        accesoriesbox1 = new javax.swing.JComboBox<>();
        accesoriesbox2 = new javax.swing.JComboBox<>();
        accesoriesbox3 = new javax.swing.JComboBox<>();
        accesoriesbox4 = new javax.swing.JComboBox<>();
        accesoriesbox5 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        jLabel3.setFont(new java.awt.Font("Chakra Petch", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Horse 1");

        jLabel4.setFont(new java.awt.Font("Chakra Petch", 0, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Horse 2");

        horse1NameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horse1NameFieldActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Chakra Petch", 0, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Horse 3");

        horse1CoatComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Coat", "Red Roan", "Palomino", "Piebald", "Buckskin" }));
        horse1CoatComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horse1CoatComboBoxActionPerformed(evt);
            }
        });

        horse2CoatComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Coat", "Red Roan", "Palomino", "Piebald", "Buckskin" }));
        horse2CoatComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horse2CoatComboBoxActionPerformed(evt);
            }
        });

        horse3CoatComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Coat", "Red Roan", "Palomino", "Piebald", "Buckskin" }));
        horse3CoatComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horse3CoatComboBoxActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Chakra Petch", 0, 13)); // NOI18N
        jButton1.setText("set");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        horse1Confidence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horse1ConfidenceActionPerformed(evt);
            }
        });

        horse4Confidence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horse4ConfidenceActionPerformed(evt);
            }
        });

        horse4CoatComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Coat", "Red Roan", "Palomino", "Piebald", "Buckskin" }));
        horse4CoatComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horse4CoatComboBoxActionPerformed(evt);
            }
        });

        horse4NameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horse4NameFieldActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Chakra Petch", 0, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Horse 4");

        horse5CoatComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Coat", "Red Roan", "Palomino", "Piebald", "Buckskin" }));
        horse5CoatComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horse5CoatComboBoxActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Chakra Petch", 0, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Horse 5");

        horsesNum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5" }));
        horsesNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horsesNumActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Chakra Petch", 0, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Race Length:");

        jLabel9.setFont(new java.awt.Font("Chakra Petch", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Name");

        jLabel10.setFont(new java.awt.Font("Chakra Petch", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Accessory");

        jLabel11.setFont(new java.awt.Font("Chakra Petch", 0, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("(between 0 and 1)");

        jLabel12.setFont(new java.awt.Font("Chakra Petch", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Confidece");

        jButton3.setFont(new java.awt.Font("Chakra Petch", 0, 13)); // NOI18N
        jButton3.setText("back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Chakra Petch", 0, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Number of horses in the race:");

        accesoriesbox1.setFont(new java.awt.Font("Chakra Petch", 0, 13)); // NOI18N
        accesoriesbox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select ", "Saddle", "Blanket", "Earplugs" }));
        accesoriesbox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accesoriesbox1ActionPerformed(evt);
            }
        });

        accesoriesbox2.setFont(new java.awt.Font("Chakra Petch", 0, 13)); // NOI18N
        accesoriesbox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select ", "Saddle", "Blanket", "Earplugs" }));

        accesoriesbox3.setFont(new java.awt.Font("Chakra Petch", 0, 13)); // NOI18N
        accesoriesbox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select ", "Saddle", "Blanket", "Earplugs" }));

        accesoriesbox4.setFont(new java.awt.Font("Chakra Petch", 0, 13)); // NOI18N
        accesoriesbox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select ", "Saddle", "Blanket", "Earplugs" }));

        accesoriesbox5.setFont(new java.awt.Font("Chakra Petch", 0, 13)); // NOI18N
        accesoriesbox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select ", "Saddle", "Blanket", "Earplugs" }));
        accesoriesbox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accesoriesbox5ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Chakra Petch", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Coat");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel13)
                .addGap(8, 8, 8)
                .addComponent(horsesNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel8)
                .addGap(4, 4, 4)
                .addComponent(lengthField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addGap(66, 66, 66)
                .addComponent(jLabel9)
                .addGap(73, 73, 73)
                .addComponent(jLabel14)
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(28, 28, 28)
                .addComponent(jLabel10))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addGap(17, 17, 17)
                .addComponent(horse1NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(horse1CoatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(horse1Confidence, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(accesoriesbox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addGap(15, 15, 15)
                .addComponent(horse2NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(horse2CoatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(horse2Confidence, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(accesoriesbox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addGap(14, 14, 14)
                .addComponent(horse3NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(horse3CoatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(horse3Confidence, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(accesoriesbox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel6)
                .addGap(15, 15, 15)
                .addComponent(horse4NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(horse4CoatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(horse4Confidence, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(accesoriesbox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel7)
                .addGap(14, 14, 14)
                .addComponent(horse5NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(horse5CoatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(horse5Confidence, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(accesoriesbox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(525, 525, 525)
                .addComponent(jLabel1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jButton3)
                .addGap(368, 368, 368)
                .addComponent(jButton1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horsesNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lengthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2))
                    .addComponent(jLabel9)
                    .addComponent(jLabel14)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel11))
                    .addComponent(jLabel12)
                    .addComponent(jLabel10))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(horse1NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horse1CoatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horse1Confidence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accesoriesbox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(horse2NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horse2CoatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horse2Confidence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accesoriesbox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(horse3NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horse3CoatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horse3Confidence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accesoriesbox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6))
                    .addComponent(horse4NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horse4CoatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horse4Confidence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accesoriesbox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7))
                    .addComponent(horse5NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horse5CoatComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horse5Confidence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accesoriesbox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addComponent(jButton1)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
        JTextField[] horseNameFields = {horse1NameField, horse2NameField, horse3NameField, horse4NameField, horse5NameField};
        JTextField[] horseConfidenceFields = {horse1Confidence, horse2Confidence, horse3Confidence, horse4Confidence, horse5Confidence};
        List<JComboBox<String>> horseAccessories = new ArrayList<>();

        // Add JComboBox objects to the list
        horseAccessories.add(accesoriesbox1);
        horseAccessories.add(accesoriesbox2);
        horseAccessories.add(accesoriesbox3);
        horseAccessories.add(accesoriesbox4);
        horseAccessories.add(accesoriesbox5);
        

        for (int i = 0; i < horsesNum.getSelectedIndex()-1; i++) {
            
            if (horseNameFields[i].getText()!=null && horseConfidenceFields[i].getText()!=null) {  
                String horseName = horseNameFields[i].getText();
                String confidenceText = horseConfidenceFields[i].getText();
                double confidence = Double.parseDouble(confidenceText);
                if (horseAccessories.get(i).getSelectedItem() != "Select") {
                        // Assuming horseConfidence is the confidence field of the Horse class
                        // You need to replace it with your actual confidence field
                        confidence += 0.1;
                        if (confidence>1) {
                            confidence = 1;
                        }
                    }
                horseConfidence.put(horseName, confidence);
                   
                }
            }
        
       // Check if there are no valid horse names entered
        boolean allEmpty = true;
        int num=0;
        for (int i = 0; i < horsesNum.getSelectedIndex() - 1; i++) {
            if (!horseNameFields[i].getText().isEmpty()) {
                allEmpty = false;
                
            } else {
                num++;
            }
        }
        if (allEmpty || num==1 || lengthField.getText().isEmpty()) {
            // Show error message and return without proceeding
            JOptionPane.showMessageDialog(this, "Please enter at least two horse name and set a race length", "Invalid Input", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Create and show the race GUI
        System.out.println(horseData.toString());
        int len = Integer.parseInt(lengthField.getText()) > 130 ? 130 : Integer.parseInt(lengthField.getText());
        RaceGUI raceGUI = new RaceGUI(horseData, horseConfidence, len);
        raceGUI.setVisible(true);


        // Close the settings page
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void horse1NameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horse1NameFieldActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_horse1NameFieldActionPerformed

    
    private void horse1CoatComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horse1CoatComboBoxActionPerformed
        // TODO add your handling code here:
        // Retrieve the selected coat from the combo box
        
        String selectedCoat = (String) horse1CoatComboBox.getSelectedItem();
        if (!selectedCoat.equals("Select Coat")) {
            ImageIcon icon = null;

            // Determine the ImageIcon based on the selected coat
            switch (selectedCoat) {
                case "Red Roan":
                    icon = new ImageIcon(getClass().getResource("/redRoan copy.png"));
                    break;
                case "Palomino":
                    icon = new ImageIcon(getClass().getResource("/palomino copy.png"));
                    break;
                case "Piebald":
                    icon = new ImageIcon(getClass().getResource("/pieBald copy.png"));
                    break;
                case "Buckskin":
                    icon = new ImageIcon(getClass().getResource("/buckskin copy.png"));
                default:
                    break;
            }

            // Debugging statements
            System.out.println("Selected coat: " + selectedCoat);
            System.out.println("Horse name: " + horse1NameField.getText());

            // Put the selected ImageIcon into the horseData map
            horseData.put(horse1NameField.getText(), icon);
        }
        
        
    }//GEN-LAST:event_horse1CoatComboBoxActionPerformed

    
    private void updateCoatComboBox(JTextField nameField, JComboBox<String> coatComboBox) {
        if (!nameField.getText().isEmpty()) {
            coatComboBox.setEnabled(true);
        } else {
            coatComboBox.setEnabled(false);
            coatComboBox.setSelectedIndex(0); // Reset selection when name field is cleared
        }
    }

    private void horse2CoatComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horse2CoatComboBoxActionPerformed
        // TODO add your handling code here:
        
        // Retrieve the selected coat from the combo box
        String selectedCoat = (String) horse2CoatComboBox.getSelectedItem();
        if (!selectedCoat.equals("Select Coat")) {

            ImageIcon icon = null;

            // Determine the ImageIcon based on the selected coat
            switch (selectedCoat) {
                case "Red Roan":
                    icon = new ImageIcon(getClass().getResource("/redRoan copy.png"));
                    break;
                case "Palomino":
                    icon = new ImageIcon(getClass().getResource("/palomino copy.png"));
                    break;
                case "Piebald":
                    icon = new ImageIcon(getClass().getResource("/pieBald copy.png"));
                    break;
                case "Buckskin":
                    icon = new ImageIcon(getClass().getResource("/buckskin copy.png"));
                default:
                    break;
            }

            // Debugging statements
            System.out.println("Selected coat: " + selectedCoat);
            System.out.println("Horse name: " + horse2NameField.getText());
            // Put the selected ImageIcon into the horseData map
            horseData.put(horse2NameField.getText(), icon);
        }
    }//GEN-LAST:event_horse2CoatComboBoxActionPerformed

    private void horse3CoatComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horse3CoatComboBoxActionPerformed
        // TODO add your handling code here:
        // Retrieve the selected coat from the combo box
        String selectedCoat = (String) horse3CoatComboBox.getSelectedItem();
        if (!selectedCoat.equals("Select Coat")) {

            ImageIcon icon = null;


            // Determine the ImageIcon based on the selected coat
            switch (selectedCoat) {
                case "Red Roan":
                    icon = new ImageIcon(getClass().getResource("/redRoan copy.png"));
                    break;
                case "Palomino":
                    icon = new ImageIcon(getClass().getResource("/palomino copy.png"));
                    break;
                case "Piebald":
                    icon = new ImageIcon(getClass().getResource("/pieBald copy.png"));
                    break;
                case "Buckskin":
                    icon = new ImageIcon(getClass().getResource("/buckskin copy.png"));
                    
                default:
                    break;
            }
            // Debugging statements
            System.out.println("Selected coat: " + selectedCoat);
            System.out.println("Horse name: " + horse3NameField.getText());
            // Put the selected ImageIcon into the horseData map
            horseData.put(horse3NameField.getText(), icon);
        }
    }//GEN-LAST:event_horse3CoatComboBoxActionPerformed

    private void horse4CoatComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horse4CoatComboBoxActionPerformed
        // TODO add your handling code here:
        // Retrieve the selected coat from the combo box
        String selectedCoat = (String) horse4CoatComboBox.getSelectedItem();
        if (!selectedCoat.equals("Select Coat")) {

            ImageIcon icon = null;


            // Determine the ImageIcon based on the selected coat
            switch (selectedCoat) {
                case "Red Roan":
                    icon = new ImageIcon(getClass().getResource("/redRoan copy.png"));
                    break;
                case "Palomino":
                    icon = new ImageIcon(getClass().getResource("/palomino copy.png"));
                    break;
                case "Piebald":
                    icon = new ImageIcon(getClass().getResource("/pieBald copy.png"));
                    
                case "Buckskin":
                    icon = new ImageIcon(getClass().getResource("/buckskin copy.png"));
                    break;
                default:
                    break;
            }
            // Debugging statements
            System.out.println("Selected coat: " + selectedCoat);
            System.out.println("Horse name: " + horse4NameField.getText());
            // Put the selected ImageIcon into the horseData map
            horseData.put(horse4NameField.getText(), icon);
        }
        
    }//GEN-LAST:event_horse4CoatComboBoxActionPerformed

    private void horse5CoatComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horse5CoatComboBoxActionPerformed
        // TODO add your handling code here:
        // Retrieve the selected coat from the combo box
        String selectedCoat = (String) horse4CoatComboBox.getSelectedItem();
        if (!selectedCoat.equals("Select Coat")) {

            ImageIcon icon = null;


            // Determine the ImageIcon based on the selected coat
            switch (selectedCoat) {
                case "Red Roan":
                    icon = new ImageIcon(getClass().getResource("/redRoan copy.png"));
                    break;
                case "Palomino":
                    icon = new ImageIcon(getClass().getResource("/palomino copy.png"));
                    break;
                case "Piebald":
                    icon = new ImageIcon(getClass().getResource("/pieBald copy.png"));
                    
                case "Buckskin":
                    icon = new ImageIcon(getClass().getResource("/buckskin copy.png"));
                    break;
                default:
                    break;
            }
            // Debugging statements
            System.out.println("Selected coat: " + selectedCoat);
            System.out.println("Horse name: " + horse5NameField.getText());
            // Put the selected ImageIcon into the horseData map
            horseData.put(horse5NameField.getText(), icon);
        }
    }//GEN-LAST:event_horse5CoatComboBoxActionPerformed

    private void horsesNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horsesNumActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_horsesNumActionPerformed

    private void horse4NameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horse4NameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horse4NameFieldActionPerformed

    private void horse4ConfidenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horse4ConfidenceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_horse4ConfidenceActionPerformed

    private void horse1ConfidenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horse1ConfidenceActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_horse1ConfidenceActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void accesoriesbox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accesoriesbox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accesoriesbox5ActionPerformed

    private void accesoriesbox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accesoriesbox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accesoriesbox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(setHorses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(setHorses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(setHorses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(setHorses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new setHorses().setVisible(true);
            }
        });
        
        
        
    }
    
    private static class BecomingRedDocumentListener implements DocumentListener {
        private JTextField textField;
        private JButton setButton;

        public BecomingRedDocumentListener(JTextField textField, JButton setButton) {
            this.textField = textField;
            this.setButton = setButton;
        }

        @Override
        public void insertUpdate(DocumentEvent e) {
            updateComponents();
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            updateComponents();
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
            updateComponents();
        }

        private void updateComponents() {
            String text = textField.getText();
            try {
                double value = Double.parseDouble(text);
                if (value < 0 || value > 1) {
                    textField.setBackground(Color.RED);
                    setButton.setEnabled(false); // Disable the set button
                } else {
                    textField.setBackground(Color.WHITE);
                    setButton.setEnabled(true); // Enable the set button
                }
            } catch (NumberFormatException ex) {
                textField.setBackground(Color.RED);
                setButton.setEnabled(false); // Disable the set button
            }
        }
    }


    
    private class enablingCombo1 implements DocumentListener {

        private final JTextField textField;

        public enablingCombo1(JTextField textField) {
            this.textField = textField;
        }
        @Override
        public void insertUpdate(DocumentEvent e) {
            updateCoatComboBox(horse1NameField, horse1CoatComboBox);

        }
        @Override
        public void removeUpdate(DocumentEvent e) {
             updateCoatComboBox(horse1NameField, horse1CoatComboBox);
        }
        @Override
        public void changedUpdate(DocumentEvent e) {
        }
    }
    
    
    private class enablingCombo2 implements DocumentListener {

        private final JTextField textField;

        public enablingCombo2(JTextField textField) {
            this.textField = textField;
        }
        @Override
        public void insertUpdate(DocumentEvent e) {
            updateCoatComboBox(horse2NameField, horse2CoatComboBox);

        }
        @Override
        public void removeUpdate(DocumentEvent e) {
             updateCoatComboBox(horse2NameField, horse2CoatComboBox);
        }
        @Override
        public void changedUpdate(DocumentEvent e) {
        }
    }
    
    private class enablingCombo3 implements DocumentListener {

        private final JTextField textField;

        public enablingCombo3(JTextField textField) {
            this.textField = textField;
        }
        @Override
        public void insertUpdate(DocumentEvent e) {
            updateCoatComboBox(horse3NameField, horse3CoatComboBox);

        }
        @Override
        public void removeUpdate(DocumentEvent e) {
             updateCoatComboBox(horse3NameField, horse3CoatComboBox);
        }
        @Override
        public void changedUpdate(DocumentEvent e) {
        }
        
        
    }
    
    private class enablingCombo4 implements DocumentListener {

        private final JTextField textField;

        public enablingCombo4(JTextField textField) {
            this.textField = textField;
        }
        @Override
        public void insertUpdate(DocumentEvent e) {
            updateCoatComboBox(horse3NameField, horse4CoatComboBox);

        }
        @Override
        public void removeUpdate(DocumentEvent e) {
             updateCoatComboBox(horse3NameField, horse4CoatComboBox);
        }
        @Override
        public void changedUpdate(DocumentEvent e) {
        }
        
        
    }
    
    private class enablingCombo5 implements DocumentListener {

        private final JTextField textField;

        public enablingCombo5(JTextField textField) {
            this.textField = textField;
        }
        @Override
        public void insertUpdate(DocumentEvent e) {
            updateCoatComboBox(horse3NameField, horse5CoatComboBox);

        }
        @Override
        public void removeUpdate(DocumentEvent e) {
             updateCoatComboBox(horse3NameField, horse5CoatComboBox);
        }
        @Override
        public void changedUpdate(DocumentEvent e) {
        }
        
        
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> accesoriesbox1;
    private javax.swing.JComboBox<String> accesoriesbox2;
    private javax.swing.JComboBox<String> accesoriesbox3;
    private javax.swing.JComboBox<String> accesoriesbox4;
    private javax.swing.JComboBox<String> accesoriesbox5;
    private javax.swing.JComboBox<String> horse1CoatComboBox;
    private javax.swing.JTextField horse1Confidence;
    private javax.swing.JTextField horse1NameField;
    private javax.swing.JComboBox<String> horse2CoatComboBox;
    private javax.swing.JTextField horse2Confidence;
    private javax.swing.JTextField horse2NameField;
    private javax.swing.JComboBox<String> horse3CoatComboBox;
    private javax.swing.JTextField horse3Confidence;
    private javax.swing.JTextField horse3NameField;
    private javax.swing.JComboBox<String> horse4CoatComboBox;
    private javax.swing.JTextField horse4Confidence;
    private javax.swing.JTextField horse4NameField;
    private javax.swing.JComboBox<String> horse5CoatComboBox;
    private javax.swing.JTextField horse5Confidence;
    private javax.swing.JTextField horse5NameField;
    private javax.swing.JComboBox<String> horsesNum;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lengthField;
    // End of variables declaration//GEN-END:variables
}
